version: 1.0.{build}
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
skip_tags: true
image: Ubuntu

install:
  - cd backend
  - pwd
  - dotnet --version

before_build:
  - dotnet restore  -v Minimal

build_script:
  # ./Paragonr.WebApi/bin/Release/netcoreapp3.0/publish/
  - dotnet publish -c Release

artifacts:
  - path: "/Paragonr.WebApi/bin/Release/netcoreapp3.0/publish/"
    name: ParagonrApiArtifacts
    type: WebDeployPackage

deploy:
  - provider: Environment
    name: ParagonrApiDeploy
    on:
      branch: master
