version: 1.0.{build}
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

skip_tags: true
image: Ubuntu1804

configuration: Release

install:
  - cd backend
  - dotnet --version

before_build:
  - dotnet restore  -v Minimal

build_script:
  - dotnet build -c %CONFIGURATION%
