version: 1.0.{build}
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
skip_tags: true
image: Ubuntu

install:
  - cd backend
  - pwd
  - dotnet --version

before_build:
  - dotnet restore  -v Minimal

build_script:
  - dotnet build -c Release
